let allApps=[],active="All";const $=s=>document.querySelector(s);
async function init(){try{allApps=await fetch("./apps.json",{cache:"no-store"}).then(r=>r.json());renderFilters();render();renderDock();const mc=$("#mobileCount");if(mc)mc.textContent=`${allApps.length} apps`}catch(e){$("#apps").innerHTML="<p>Unable to load apps.</p>"}}
function recentIds(){try{return JSON.parse(localStorage.getItem("webspace-recent")||"[]")}catch{return[]}}
function renderFilters(){const cats=["All",...new Set(allApps.map(a=>a.category))];$("#filters").innerHTML=cats.map(c=>`<button class="${c===active?"active":""}" data-cat="${c}">${c}</button>`).join("");$("#filters").onclick=e=>{if(!e.target.dataset.cat)return;active=e.target.dataset.cat;renderFilters();render()}}
function iconMarkup(a){if(a.iconUrl)return `<img src="${a.iconUrl}" alt="" onerror="this.style.display=\'none\'">`;return a.icon||"W"}
function card(a){return `<button class="card" data-id="${a.id}" style="--tint:${a.tint}"><div class="icon">${iconMarkup(a)}</div><h3>${a.name}</h3><p>${a.description}</p><span class="tag">${a.category}</span></button>`}
function render(){const search=$("#search"),q=search?search.value.trim().toLowerCase():"";const apps=allApps.filter(a=>(active==="All"||a.category===active)&&(!q||[a.name,a.description,a.category].join(" ").toLowerCase().includes(q)));$("#empty").hidden=!!apps.length;$("#apps").innerHTML=apps.map(card).join("")}
function renderDock(){const ids=recentIds();const open=allApps.filter(a=>ids.includes(a.id)).slice(0,5);$("#dock").innerHTML=open.map(a=>`<button data-id="${a.id}" title="${a.name}" style="--tint:${a.tint}">${iconMarkup(a)}</button>`).join("");$("#dock").classList.toggle("show",open.length>0)}
function openApp(id){const a=allApps.find(x=>x.id===id);if(!a)return;if(a.open==="external"){window.open(a.url,"_blank","noopener");return}$("#viewerTitle").textContent=a.name;$("#viewerUrl").textContent=a.url;$("#external").href=a.url;$("#viewer").hidden=false;document.body.style.overflow="hidden";$("#frame").src=a.url;try{const recent=recentIds().filter(x=>x!==id);localStorage.setItem("webspace-recent",JSON.stringify([id,...recent].slice(0,6)));renderDock()}catch{}}
function closeApp(){$("#viewer").hidden=true;$("#frame").src="about:blank";document.body.style.overflow="";render()}
function appClick(e){const c=e.target.closest(".card");if(c)openApp(c.dataset.id)}
$("#apps").onclick=appClick;$("#dock").onclick=appClick;const search=$("#search");if(search)search.addEventListener("input",render);$("#close").onclick=closeApp;$("#about").onclick=()=>$("#modal").hidden=false;$("#modalClose").onclick=()=>$("#modal").hidden=true;$("#modal").onclick=e=>{if(e.target.id==="modal")$("#modal").hidden=true};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeApp()});init();
const edit=$("#editHome");if(edit)edit.onclick=()=>{document.body.classList.toggle("home-edit");edit.textContent=document.body.classList.contains("home-edit")?"Done":"•••"};
function updateHomeClock(){const d=new Date();const t=$("#homeTime"),dt=$("#homeDate");if(t)t.textContent=d.toLocaleTimeString("zh-TW",{hour:"2-digit",minute:"2-digit",hour12:false});if(dt)dt.textContent=d.toLocaleDateString("zh-TW",{month:"long",day:"numeric",weekday:"short"})}updateHomeClock();setInterval(updateHomeClock,30000);
const homeWx=(c,d=1)=>c===0?[d?"☀️":"🌙","晴朗"]:c<=2?[d?"🌤️":"☁️","晴時多雲"]:c===3?["☁️","陰天"]:c<=48?["🌫️","霧"]:c<=57?["🌦️","毛毛雨"]:c<=67?["🌧️","雨"]:c<=77?["🌨️","雪"]:c<=82?["🌦️","陣雨"]:c<=86?["🌨️","陣雪"]:["⛈️","雷雨"];
async function loadHomeWeather(){const set=(s,v)=>{const e=$(s);if(e)e.textContent=v};try{const p=await new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(ok,no,{timeout:7000,maximumAge:900000})),{latitude,longitude}=p.coords,q=new URLSearchParams({latitude,longitude,timezone:"auto",forecast_days:"1",current:"temperature_2m,is_day,weather_code",daily:"temperature_2m_max,temperature_2m_min"}),r=await fetch("https://api.open-meteo.com/v1/forecast?"+q);if(!r.ok)throw 0;const x=await r.json(),w=homeWx(+x.current.weather_code,+x.current.is_day);set("#homeWeatherIcon",w[0]);set("#homeTemp",Math.round(x.current.temperature_2m)+"°");set("#homeWeatherText",w[1]);set("#homeRange","H:"+Math.round(x.daily.temperature_2m_max[0])+"° L:"+Math.round(x.daily.temperature_2m_min[0])+"°")}catch(e){set("#homeWeatherText","天氣暫時無法取得");set("#homeRange","開啟 Weather 查看")}}loadHomeWeather();